version: "3.8"
services:

    testing_snmpd:
        build:
            context: ./dock_snmpd
            dockerfile: Dockerfile
        networks:
            - the_network
        container_name: testing_snmpd


    test:
        build:
            context: ./dock_test
            dockerfile: Dockerfile
        networks:
            - the_network
        container_name: test



networks:
    the_network:
        name: the_network
        driver: bridge

